IMG_PATH = "../common/dataset/"
IMG_HEIGHT = 68
IMG_WEDTH = 68

SEED = 42
TRAIN_RATIO = 0.75
TEST_RATIO = 1 - TRAIN_RATIO
NOISE_FACTOR = 0.5

LEARNING_RATE = 1e-3
EPOCHS = 20
TRAIN_BATCH_SIZE = 32
TEST_BATCH_SIZE = 32

PROJECT_PACKAGE_NAME = "image_denoising"
DENOISER_MODEL_NAME = "denoiser.pt"